FORMAT: 1A
HOST: http://localhost:21092/

# Restaurant API

API Rest para ações de cadastro, edição e exclusão de restaurantes e seus produtos.

## Restaurantes [/public/restaurant/]

### Listar todos restaurantes [GET]

+ Response 200 (application/json)

        [
            {
            "id_restaurant": 1,
            "url_image_restaurant": "",
            "restaurant_name": "Nome restaurante",
            "street": "Rua XYZ",
            "neighborhood": "Centro",
            "number": "1000",
            "zipcode": "98787000",
            "city": "Cidade"
            },
            {
            "id_restaurant": 2,
            "url_image_restaurant": "",
            "restaurant_name": "Nome restaurante 2",
            "street": "Rua XYZ",
            "neighborhood": "Centro",
            "number": "1000",
            "zipcode": "98787000",
            "city": "Cidade"
            }
        ]

### Cadastrar restaurante [POST]

+ Request (application/json)

        {
            "url_image_restaurant": "imagem-do-restaurante.png"
            "restaurant_name": "Nome do restaurante",
            "street": "Rua XYZ",
            "neighborhood": "Bairro",
            "city": "Cidade",
            "number": "Número do endereço",
            "zipcode": "Cep do endereço"
        }

+ Response 201 (application/json)

    + Body

            {
               success: true
            }